name : Java & Docker & Maven

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: ./mvnw clean package
      - name: Build Docker image
        run: |
          docker build -t my-spring-boot-app .
          docker tag my-spring-boot-app my-docker-registry/my-spring-boot-app
          docker push my-docker-registry/my-spring-boot-app
